name: svv-gui
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.13
  - pyside6>=6.4
  - pyvista>=0.41
  - pyvistaqt>=0.11.0
  - vtk
  - mesalib
  - libglvnd
  - libxcb
  - xorg-libx11
  - xorg-libxt
  - xorg-libxfixes
  - numpy
  - psutil
  - pip
  - pip:
      - .
